### ISSUE TITLE
skip map failures

### ISSUE THREAD

**Issue by bebbi** [commontk/dcmjs.org#10]
Looking at the full process, there's one feature missing (all mentioned options and return values below exist, but the logic to write vs skip is missing):
// after mapDom

if (options.keepMappingFailures === false) {
   if (result.status.mapFailed) {
       //need logic to skip file (i.e., not add it to the zip set)
   }
}

**Comment by pieper** [comment]
Agreed.  Can you add that?

**Comment by bebbi** [comment]
fixed in f017f9a
