### ISSUE TITLE
chrome gets stuck after reading

### ISSUE THREAD

**Issue by bebbi** [commontk/dcmjs.org#11]
not sure if same as #9, so it gets it's own issue. I did another test run on a very large dataset of size n. I just saw it count to almost the end (very good performance there) - could very well be n-1 or n - and then displaying "ignoring hidden file/directory: .DS_Store", and getting stuck there. No error message, but the browser tab (not the browser as a whole) is getting completely locked. CPU resources spike very high for a long time (presumably before I'm going to kill it). Here, I suspect the jqGrid is the guilty - can we avoid too much data in jqGrid or should we even completely skip it for the purpose of this run?

**Comment by pieper** [comment]
Just pushed new version that bypasses jqGrid and instead uses a filePathObjects global.  Now the filePaths are only put in the jqGrid if there are fewer than 1000.  Probably we should get rid of the jqGrid code entirely for this purpose (but it's a good tool that we might want to use for a header browser or something).

**Comment by bebbi** [comment]
yes - I think we'll want to display info on various module levels, but likely never on a per file level.
Closing this for now - could also be related to fixed #8
