### ISSUE TITLE
Improve transparency of the output directory structure configuration

### ISSUE THREAD

**Issue by fedorov** [commontk/dcmjs.org#22]
you might want to consider is to use DICOM tags for defining the structure of the organized data. I think the approach used by CTP for this purpose [1] is more transparent than the one in dcmjs [2].

[1] "This example shows tags for PatientID/AccessionNumber/StudyInstanceUID: (0010,0020)/[00080050]/(0020,000D)", see http://mircwiki.rsna.org/index.php?title=CTP-The_RSNA_Clinical_Trial_Processor#DirectoryStorageService

[2] trialname/centersubj/dicomstudyid/dicomseriesid/

**Comment by bebbi** [comment]
unlike CTP, we support identifiers parsed from file path, these are the source of [2].
Use-case: large dataset where we know path is correct, but DICOM identifiers may not be (that's a typical Pharma use-case because subject IDs almost always stems from sources that never undergo trial specific content or format checks.)

Actually, your [2] quote is from the place where the user assigns variable names to path elements for later re-use in the anonymization/mapping code.
This definitely deserves clean-up, more clarification, etc.

**Comment by fedorov** [comment]
> unlike CTP, we support identifiers parsed from file path

Oh, I see! Would it make sense to support both file-path and DICOM tags?

I am saving the results of anonymization into the user-defined hierarchy. Since the data has been de-identified, the IDs are assigned by the de-id procedure, so by the process they are well-defined.

**Comment by bebbi** [comment]
we already do this.
[2] actually means nothing else than:
"let the first component of the file path be the value of a new variable called "trialname"
"let the second component of the file path be the value of a new variable called "centersubj"
..etc..
Then, in the script window, you can work with a regular variable called trialname and assign it to a DICOM tag.
In the same script window, you can also assign this, or any DICOM tag, or anything else back to the output file path of the cleaned DICOM.

**Comment by fedorov** [comment]
wouldn't it be easier if the user could refer to a specific DICOM tag directly in the path config? 

I may be biased, but I think in most cases users would want to configure the directory structure based on DICOM tags, not on other things. The point is to make the most common use case the easiest to implement. 

Either way is fine, it's just a feedback.

**Comment by bebbi** [comment]
not sure but I think we might be talking about a doc issue here.
user can specify DICOM tag in the _output_ path config.
for clarities sake, the “folder pattern” should really be renamed to “incoming folder pattern”. You can simply leave that pattern empty if you have no use for _incoming_ file path components in your mapping config.

**Comment by fedorov** [comment]
NOW I see where I missed it... sorry for the noise!
