### ISSUE TITLE
file grouping of output by zipFileName

### ISSUE THREAD

**Issue by bebbi** [commontk/dcmjs.org#5]
use mapDom zipFileName to group files into zips, optionally making multiple zips with numeric extension to zipFileName if too many files in the same group.

**Comment by pieper** [comment]
This will require a little restructuring.  Is it okay as-is for now?  If not, the next easier thing to do would be to swtich to only using the zipfile name from the mapper.  Handling both the numbered names and the optional name from the mapper is some extra logic to track.

**Comment by bebbi** [comment]
What's your amount? If large, maybe lets switch to names for this exercise only..

**Comment by pieper** [comment]
More than I have today : )

Problem is that it requires changing things so we track the old name of the
zip file and detect that it's a new zipfile before adding the current file
to it.  So there's rearranging of code blocks, chance of errors, and
testing to do.

**Comment by bebbi** [comment]
ok lets look into this another time

**Comment by bebbi** [comment]
I need that to bookkeep a large dataset where browser could crash in the middle. Implemented in 59d067b.
Also adds and empties mapping log for every zip file created (same name, .txt extension).
Also, reduce files in zip to 5000 for now.
