### ISSUE TITLE
review structural dicom tags not in CTP profile

### ISSUE THREAD

**Issue by bebbi** [commontk/dcmjs.org#6]
Do you see any other "special" DICOM (file) tags to keep in a "only keep explicitly mentioned tags" scenario?CTP doesn't explicitely deal with below so we should add them to our (CTP based) config. So far we've got:
    "Item",
    "ItemDelimitationItem",
    "SequenceDelimitationItem",
    "GenericGroupLength",
    “PixelData”

**Comment by pieper** [comment]
I think those are all special cases and should always be kept.  The Item and group related ones are basically like punctuation.  PixelData is a special case that is assumed to be kept.

**Comment by bebbi** [comment]
Yes indeed, the issue is just to check if more of this structural kind come to mind?

**Comment by pieper** [comment]
Not off the top of my head.

**Comment by bebbi** [comment]
close for now, suggestions welcome at any time
