### ISSUE TITLE
download log

### ISSUE THREAD

**Issue by bebbi** [commontk/dcmjs.org#7]
some way of downloading stuff created by mapDom and returned as return_value.status.log
Important here to verify keepOnlyExplicitTags is not removing too much (will manually analyze the log for now)

**Comment by pieper** [comment]
Log is now displayed on page.  Let me know if this isn't enough.

**Comment by bebbi** [comment]
It's not ideal, it'll have millions of rows and may slow down things again. I'll then need it to extract all different removed tags in order to QC that not too much was removed- copy pasting from dom seems not an option. Any other possibilities?

**Comment by pieper** [comment]
Was going to try making it a different download option.  I guess we could
add a button that is enabled if there is a log file and then trigger a
download from the callback.  The log might still be big, but it would be in
memory and not in the DOM.

**Comment by bebbi** [comment]
that would be excellent

**Comment by bebbi** [comment]
the required mapDom log is in result.status.log btw.
How about even simpler: collect the log in a variable, and on button click, open a new tab with it (e.g. jsonified)?
