### ISSUE TITLE
zip file never gets created

### ISSUE THREAD

**Issue by bebbi** [commontk/dcmjs.org#9]
In a folder set of 15 files, process stops after this message: -- 14 of 15 processed (93%)
No bug, just stops. I think it's related to other zip file bug.
(I tested on your latest commit ce148b5, not my subsequent ones - it's present on all versions).

**Comment by bebbi** [comment]
there may be a connection with the fact that if I drag n single files (no folders) into the dropzone, only (n-1) get displayed. Eg, if n=1, it's 0 despite the message "found 1 files so far".
I just verified again that behaviour is identical on ce148b5 as well as gh-pages latest

**Comment by pieper** [comment]
I just tried the current version with a single file dropped and it worked fine.  Also just tested 1998 files and the zip was generated fine.

It may be that the scrollback buffer of the developer tools console is getting huge and ultimately hangs.  We may want to try using console.clear().  I thought there was a limit on how many lines of scrollback it keeps, but I don't find a document for that.

**Comment by bebbi** [comment]
When I reload the page and add a folder with even <10 dicoms, it stops at 90% most of the time. It does appear to be specific to the folder I choose - maybe a non dicom file that comes last or at a special position will stop it, or something like that?

**Comment by bebbi** [comment]
I was testing with small number of files. But the newest version appears to fix it for all failed tests I have. I’ll do more testing

**Comment by bebbi** [comment]
currently not happening. Possibly related to #8 which is fixed now. Closing and re-opening if necessary
